# backend/Dockerfile

# Etapa 1: Build da aplicação
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install -g @nestjs/cli
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: Produção
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY package*.json tsconfig.json ./
RUN npm install -g @nestjs/cli

# RUN npm install --only=production
RUN npm install 

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
